name: elevateitnow
favicon: null
layout_spectrum: 0.38813
typography_spectrum: 0.30392
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#595959'
    - '#008dad'
    - '#a1a1a1'
    - '#40d7de'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.8810295956209302
  rhythmicContrast: 0.20575993112288415
purpose: []
